spring.datasource.url=jdbc:mysql://localhost:3306/facturacion
spring.datasource.username=root
spring.datasource.password=Alexis0991

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto (opcional, Hibernate suele detectarlo solo)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

# JWT Configuration
jwt.secret=FacturaServicioSuperSecretKey2025ForSecurityChangeMePleaseToSomethingSecure
jwt.expiration=86400000
